// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Roqeeb_Project.Context;

namespace Roqeeb_Project.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Roqeeb_Project.Entities.Admin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = "dbd0c6c8-8798-4a30-aa0e-7626c9e08447",
                            Age = 20,
                            Email = "raufroqeeb123@gmail.com",
                            FirstName = "Roqeeb",
                            IsDeleted = false,
                            LastName = "Temidayo",
                            UserId = "2803058e-1d20-40bc-9866-4664cd0c1ede"
                        });
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.AdminCart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("AdminCarts");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerId1")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<double>("CostPrice")
                        .HasColumnType("double");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsAvalaible")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("double");

                    b.Property<int>("SetLowQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductAdminCart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("AdminCartId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("AdminCartId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAdminCarts");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductCart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("AdminCartId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminCartId");

                    b.ToTable("ProductsCarts");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductPurchase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductId1")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<string>("PurchaseId1")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId1");

                    b.HasIndex("PurchaseId1");

                    b.ToTable("ProductPurchases");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductSales", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("SalesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesId");

                    b.ToTable("ProductsSales");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductSalesCart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Month")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SalesCartId")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("Week")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("SalesCartId");

                    b.ToTable("ProductSalesCarts");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductSection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("SectionId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SectionId");

                    b.ToTable("ProductSections");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Purchase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("AdminCartId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text");

                    b.Property<string>("SupplierId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("AdminCartId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Sales", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text");

                    b.Property<string>("SalesCartId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("SalesCartId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.SalesCart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Month")
                        .HasColumnType("text");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double");

                    b.Property<DateTime>("Week")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("SalesCarts");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Section", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("SectionDescription")
                        .HasColumnType("text");

                    b.Property<string>("SectionName")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("StoreDescription")
                        .HasColumnType("text");

                    b.Property<string>("StoreName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("SupplierName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Roqeeb_Project.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "fb059154-1856-40bc-8608-0b2b04e4b0a2",
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "9d88d0ab-71ec-4ff3-85eb-e776a7eb34cf",
                            IsDeleted = false,
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("Roqeeb_Project.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "2803058e-1d20-40bc-9866-4664cd0c1ede",
                            Email = "raufroqeeb123@gmail.com",
                            FirstName = "Roqeeb",
                            IsDeleted = false,
                            IsEmailConfirmed = true,
                            LastName = "Temidayo",
                            Password = "temi123Ucf0r0ay1zFDWA==",
                            Salt = "Ucf0r0ay1zFDWA==",
                            Username = "RRT"
                        });
                });

            modelBuilder.Entity("Roqeeb_Project.Identity.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = "32639f89-74f8-4482-89ec-ff8ea2a06935",
                            IsDeleted = false,
                            RoleId = "fb059154-1856-40bc-8608-0b2b04e4b0a2",
                            UserId = "2803058e-1d20-40bc-9866-4664cd0c1ede"
                        });
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Admin", b =>
                {
                    b.HasOne("Roqeeb_Project.Identity.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Roqeeb_Project.Entities.Admin", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Customer", b =>
                {
                    b.HasOne("Roqeeb_Project.Identity.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("Roqeeb_Project.Entities.Customer", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Employee", b =>
                {
                    b.HasOne("Roqeeb_Project.Identity.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("Roqeeb_Project.Entities.Employee", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Order", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.Customer", "Customer")
                        .WithMany("Order")
                        .HasForeignKey("CustomerId1");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductAdminCart", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.AdminCart", "AdminCart")
                        .WithMany("ProductAdminsCart")
                        .HasForeignKey("AdminCartId");

                    b.HasOne("Roqeeb_Project.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("AdminCart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductCart", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.AdminCart", "AdminCart")
                        .WithMany("productCarts")
                        .HasForeignKey("AdminCartId");

                    b.Navigation("AdminCart");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductPurchase", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.Product", "Product")
                        .WithMany("ProductPurchase")
                        .HasForeignKey("ProductId1");

                    b.HasOne("Roqeeb_Project.Entities.Purchase", "Purchase")
                        .WithMany()
                        .HasForeignKey("PurchaseId1");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductSales", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.Product", "Product")
                        .WithMany("ProductSales")
                        .HasForeignKey("ProductId");

                    b.HasOne("Roqeeb_Project.Entities.Sales", "Sales")
                        .WithMany("ProductSales")
                        .HasForeignKey("SalesId");

                    b.Navigation("Product");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductSalesCart", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.SalesCart", "SalesCart")
                        .WithMany("ProductSalesCarts")
                        .HasForeignKey("SalesCartId");

                    b.Navigation("SalesCart");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.ProductSection", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.Product", "Product")
                        .WithMany("productSections")
                        .HasForeignKey("ProductId");

                    b.HasOne("Roqeeb_Project.Entities.Section", "Section")
                        .WithMany("productSections")
                        .HasForeignKey("SectionId");

                    b.Navigation("Product");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Purchase", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.AdminCart", "AdminCart")
                        .WithMany()
                        .HasForeignKey("AdminCartId");

                    b.HasOne("Roqeeb_Project.Entities.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId");

                    b.Navigation("AdminCart");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Sales", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.SalesCart", "SalesCart")
                        .WithMany()
                        .HasForeignKey("SalesCartId");

                    b.Navigation("SalesCart");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Section", b =>
                {
                    b.HasOne("Roqeeb_Project.Entities.Store", "Store")
                        .WithMany("Sections")
                        .HasForeignKey("StoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Roqeeb_Project.Identity.UserRole", b =>
                {
                    b.HasOne("Roqeeb_Project.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("Roqeeb_Project.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.AdminCart", b =>
                {
                    b.Navigation("ProductAdminsCart");

                    b.Navigation("productCarts");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Customer", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Product", b =>
                {
                    b.Navigation("ProductPurchase");

                    b.Navigation("ProductSales");

                    b.Navigation("productSections");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Sales", b =>
                {
                    b.Navigation("ProductSales");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.SalesCart", b =>
                {
                    b.Navigation("ProductSalesCarts");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Section", b =>
                {
                    b.Navigation("productSections");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Store", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Roqeeb_Project.Entities.Supplier", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Roqeeb_Project.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Roqeeb_Project.Identity.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
